name: MLCrystals
channels:
  - defaults
  - conda-forge
dependencies:
  # Running Simulations
  - python=3.6
  # Dev tools
  - pytest=5.0.*
  - mypy=0.720
  - black=19.10b0
  - isort=4.3.*
  - pylint=2.3.1
  - nbdime=1.0.*
  - jupytext=1.2.*
  # Interactive analysis
  - malramsay::sdanalysis=0.11.3
  - scikit-learn==0.21.*
  - umap-learn==0.3.*
  - hdbscan~=0.8.22
  - jupyter=1.0.0
  - altair=3.1.*
  - matplotlib=3.1.*
  - pandas=0.25.*
  - pillow=6.1.*
  - selenium=3.141.*
  - phantomjs=2.1.*
  - geckodriver=0.24.0
