name: MLCrystals
channels:
  - defaults
  - conda-forge
  - malramsay
  - glotzer
dependencies:
  # Running Simulations
  - python
  # Dev tools
  - pytest
  - mypy
  - black
  - isort
  - pylint
  - nbdime
  # Interactive analysis
  - malramsay::sdanalysis=0.7.15
  - scikit-learn==0.21.*
  - jupyter
  - altair=2.*
  - nbdime>=1.0
  - matplotlib
  - pandas
  - pillow
  - selenium
  - phantomjs
